# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowsEIT.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from pickle import TRUE
from traceback import print_tb
from PyQt5 import QtCore, QtGui, QtWidgets
from numpy import rint
import numpy
import EIT.eit as TIE
import cv2



import threading


class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName("QMainWindow")
        QMainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        QMainWindow.resize(997, 819)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Img_Eit/ImgTab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QMainWindow.setWindowIcon(icon)
        QMainWindow.setAutoFillBackground(False)
        QMainWindow.setStyleSheet("background-color: rgb(217, 217, 217);")
        QMainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        QMainWindow.setIconSize(QtCore.QSize(30, 30))
        QMainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(QMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(450, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabConfig = QtWidgets.QTabWidget(self.frame)
        self.tabConfig.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabConfig.setFont(font)
        self.tabConfig.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabConfig.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabConfig.setDocumentMode(True)
        self.tabConfig.setTabsClosable(False)
        self.tabConfig.setMovable(False)
        self.tabConfig.setTabBarAutoHide(False)
        self.tabConfig.setObjectName("tabConfig")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 402, 208))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.connectDevice = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.connectDevice.setFont(font)
        self.connectDevice.setObjectName("connectDevice")
        self.gridLayout_3.addWidget(self.connectDevice, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Img_Eit/ImgTab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabConfig.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 402, 208))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.openFile = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openFile.setFont(font)
        self.openFile.setObjectName("openFile")
        self.gridLayout_2.addWidget(self.openFile, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.scrollArea_2)
        self.tabConfig.addTab(self.tab_2, icon1, "")
        self.verticalLayout.addWidget(self.tabConfig)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pbPlay = QtWidgets.QPushButton(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pbPlay.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbPlay.setFont(font)
        self.pbPlay.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pbPlay.setObjectName("pbPlay")
        self.gridLayout.addWidget(self.pbPlay, 1, 0, 1, 1)
        self.pbPause = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbPause.setFont(font)
        self.pbPause.setObjectName("pbPause")
        self.gridLayout.addWidget(self.pbPause, 1, 1, 1, 1)
        self.fileOp = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.fileOp.setFont(font)
        self.fileOp.setCheckable(True)
        self.fileOp.setObjectName("fileOp")
        self.gridLayout.addWidget(self.fileOp, 0, 0, 1, 1)
        self.pbStop = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbStop.setFont(font)
        self.pbStop.setObjectName("pbStop")
        self.gridLayout.addWidget(self.pbStop, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pbPrint = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbPrint.setFont(font)
        self.pbPrint.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pbPrint.setObjectName("pbPrint")
        self.horizontalLayout_4.addWidget(self.pbPrint)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pbRec = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbRec.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Img_Eit/ImgRec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbRec.setIcon(icon2)
        self.pbRec.setObjectName("pbRec")
        self.horizontalLayout_5.addWidget(self.pbRec)
        self.pbStopRec = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pbStopRec.setFont(font)
        self.pbStopRec.setObjectName("pbStopRec")
        self.horizontalLayout_5.addWidget(self.pbStopRec)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.eitImg = QtWidgets.QLabel(self.centralwidget)
        self.eitImg.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.eitImg.setFont(font)
        self.eitImg.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.eitImg.setText("")
        self.eitImg.setPixmap(QtGui.QPixmap("Img_Eit/LogoEit.png"))
        self.eitImg.setAlignment(QtCore.Qt.AlignCenter)
        self.eitImg.setObjectName("eitImg")
        self.horizontalLayout.addWidget(self.eitImg)
        QMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 26))
        self.menubar.setObjectName("menubar")
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QMainWindow)
        self.statusbar.setObjectName("statusbar")
        QMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QMainWindow)
        self.tabConfig.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)



        #init 
        self.pbStop.setEnabled(False) # estado do botão stop desativo
        

        #variable define
        self.initPlay = None # 
        self.routeFileCSV = None
        self.imagem = None

        #event clicked
        self.pbPlay.clicked.connect(self.playEIT)
        self.pbStop.clicked.connect(self.StopEIT)
        #self.connectDevice.clicked.connect()
        self.openFile.clicked.connect(self.getRouteFileCSV)


    def retranslateUi(self, QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QMainWindow.setWindowTitle(_translate("QMainWindow", "EIT"))
        self.connectDevice.setText(_translate("QMainWindow", "Open Connection"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.tab), _translate("QMainWindow", "EIT"))
        self.openFile.setText(_translate("QMainWindow", "Open file .CSV"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.tab_2), _translate("QMainWindow", "Open File"))
        self.label_4.setText(_translate("QMainWindow", "Start Rebuilding"))
        self.pbPlay.setText(_translate("QMainWindow", "PLAY"))
        self.pbPause.setText(_translate("QMainWindow", "PAUSE"))
        self.fileOp.setText(_translate("QMainWindow", "FILE"))
        self.pbStop.setText(_translate("QMainWindow", "STOP"))
        self.label_3.setText(_translate("QMainWindow", "Save Current Reconstructed Image"))
        self.pbPrint.setText(_translate("QMainWindow", "PRINT"))
        self.label.setText(_translate("QMainWindow", "Record Tomography"))
        self.pbRec.setText(_translate("QMainWindow", "REC"))
        self.pbStopRec.setText(_translate("QMainWindow", "STOP REC"))


    def setEnablePushButton(self, statusPlay:bool = True,
                                statusStop:bool = True,
                                statusPause:bool = True,
                                statusFile:bool = True,):
        self.pbPlay.setEnabled(statusPlay)
        self.pbStop.setEnabled(statusStop)
        self.pbPause.setEnabled(statusPause)
        self.fileOp.setEnabled(statusFile)
        pass


    def playEIT(self):
        '''
        Função executada a i clicar no botão Play.
        Ela da inicio a modelagem da imagem sendo para a
        rescontrução do arquivo ou para metodo em tempo real
        de resconstrução

        '''
        self.setEnablePushButton(statusPlay=False,
                                statusStop=True,
                                statusPause=True,
                                statusFile=False)
        self.initPlay = True
        self.showEit()
       
        pass


    def getRouteFileCSV(self):
        self.routeFileCSV = QtWidgets.QFileDialog.getOpenFileName()[0]#pega a rota ate oarquiov csv
        print(self.routeFileCSV)
        pass

    
    def StopEIT(self):
        self.setEnablePushButton(statusPlay=True,
                                statusStop=False,
                                statusPause=False,
                                statusFile=True)
        self.initPlay = False
        self.eitImg.setPixmap(QtGui.QPixmap("Img_Eit/LogoEit.png"))
        pass


    def showEit(self):

        #Verifica se o o botão File esta ativo, se sim ececuta a rescontrução de uma arquivo CSV
        if(self.fileOp.isChecked()):
            self.rebuildCSV()
            pass
        else:
            self.tieRealTime()
        pass


    def rebuildCSV(self):


        width = self.eitImg.width()
        height = self.eitImg.height()

        if width <= height:
            height = width
        else:
            width = height

        imagem = numpy.zeros((width,height,3), numpy.uint8)

        imagem = TIE.rebuildImg(width,height,RouteFile=self.routeFileCSV)

        winName = 'Janela de Teste para o SOPT'
        #cv2.namedWindow(winName, cv2.WINDOW_AUTOSIZE)

        #cv2.imshow(winName, imagem)
        
        imagem = QtGui.QImage(imagem,width,height,imagem.strides[0],QtGui.QImage.Format_RGB888)
        
        self.eitImg.setPixmap(QtGui.QPixmap.fromImage(imagem))

        cv2.waitKey(10)

        pass


    def tieRealTime(self):
        threading.Thread(target=self.updateTie).start()
        pass


    def updateTie(self):
        self.eitImg.setPixmap(QtGui.QPixmap())
        print(self.fileOp.isChecked())
        while(1):
            if not self.initPlay:
                break

    